import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service | VSHAD RoboSocial",
  description: "Terms of Service for VSHAD RoboSocial CMS",
};

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-gray-950 text-gray-100">
      <div className="max-w-4xl mx-auto px-4 py-16">
        <h1 className="text-4xl font-bold mb-8">Terms of Service</h1>
        <p className="text-gray-400 mb-8">Last updated: January 2025</p>

        <div className="space-y-8 text-gray-300">
          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">1. Acceptance of Terms</h2>
            <p>
              By accessing or using VSHAD RoboSocial (&quot;the Service&quot;), you agree to be bound by these 
              Terms of Service (&quot;Terms&quot;). If you do not agree to these Terms, do not use the Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">2. Description of Service</h2>
            <p>
              VSHAD RoboSocial is a social media content management system that provides:
            </p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>AI-powered content generation for social media posts</li>
              <li>Content scheduling and calendar management</li>
              <li>Publishing to connected social media platforms (LinkedIn, Facebook, Instagram)</li>
              <li>Company profile and brand voice management</li>
              <li>Analytics and performance tracking</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">3. User Accounts</h2>
            <h3 className="text-xl font-medium text-white mb-2">3.1 Registration</h3>
            <p>
              You may need to create an account to use certain features. You agree to provide accurate, 
              current, and complete information during registration.
            </p>

            <h3 className="text-xl font-medium text-white mb-2 mt-4">3.2 Account Security</h3>
            <p>
              You are responsible for maintaining the confidentiality of your account credentials and for 
              all activities that occur under your account.
            </p>

            <h3 className="text-xl font-medium text-white mb-2 mt-4">3.3 Social Media Connections</h3>
            <p>
              By connecting your social media accounts, you authorize us to access and publish content 
              on your behalf according to your instructions.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">4. Acceptable Use</h2>
            <p>You agree NOT to use the Service to:</p>
            <ul className="list-disc list-inside space-y-2 ml-4">
              <li>Violate any applicable laws or regulations</li>
              <li>Infringe on intellectual property rights of others</li>
              <li>Publish spam, misleading, or deceptive content</li>
              <li>Distribute malware or harmful code</li>
              <li>Harass, abuse, or harm others</li>
              <li>Violate the terms of connected social media platforms</li>
              <li>Attempt to gain unauthorized access to our systems</li>
              <li>Use automated means to access the Service beyond intended functionality</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">5. Content</h2>
            <h3 className="text-xl font-medium text-white mb-2">5.1 Your Content</h3>
            <p>
              You retain ownership of content you create or upload. By using the Service, you grant us a 
              limited license to store, process, and publish your content as directed by you.
            </p>

            <h3 className="text-xl font-medium text-white mb-2 mt-4">5.2 AI-Generated Content</h3>
            <p>
              Content generated by our AI features is provided as suggestions. You are responsible for 
              reviewing, editing, and approving all content before publishing. We do not guarantee the 
              accuracy, appropriateness, or effectiveness of AI-generated content.
            </p>

            <h3 className="text-xl font-medium text-white mb-2 mt-4">5.3 Content Responsibility</h3>
            <p>
              You are solely responsible for all content published through your connected social media 
              accounts, whether created manually or with AI assistance.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">6. Third-Party Services</h2>
            <p>
              The Service integrates with third-party platforms (LinkedIn, Facebook, Instagram, etc.). 
              Your use of these platforms is governed by their respective terms of service. We are not 
              responsible for the availability, accuracy, or policies of third-party services.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">7. Intellectual Property</h2>
            <p>
              The Service, including its design, features, and code, is owned by VSHAD and protected by 
              intellectual property laws. You may not copy, modify, distribute, or reverse engineer any 
              part of the Service.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">8. Disclaimer of Warranties</h2>
            <p>
              THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE&quot; WITHOUT WARRANTIES OF ANY KIND, 
              EXPRESS OR IMPLIED. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, 
              OR SECURE.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">9. Limitation of Liability</h2>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, 
              SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS, DATA, OR BUSINESS 
              OPPORTUNITIES, ARISING FROM YOUR USE OF THE SERVICE.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">10. Indemnification</h2>
            <p>
              You agree to indemnify and hold harmless VSHAD and its affiliates from any claims, damages, 
              or expenses arising from your use of the Service, your content, or your violation of these Terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">11. Termination</h2>
            <p>
              We may suspend or terminate your access to the Service at any time for any reason, including 
              violation of these Terms. You may stop using the Service at any time by disconnecting your 
              accounts.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">12. Changes to Terms</h2>
            <p>
              We may modify these Terms at any time. Continued use of the Service after changes constitutes 
              acceptance of the modified Terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">13. Governing Law</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of South Africa, 
              without regard to conflict of law principles.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">14. Contact</h2>
            <p>
              For questions about these Terms, please contact us at:
            </p>
            <p className="mt-2">
              <strong>Email:</strong> petrographics.adm@gmail.com
            </p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-gray-800">
          <Link 
            href="/" 
            className="text-blue-400 hover:text-blue-300 transition-colors"
          >
            ← Back to App
          </Link>
        </div>
      </div>
    </div>
  );
}